{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: strimzi-user-operator
{{- end -}}
