apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-user-operator
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: strimzi-user-operator
    app.kubernetes.io/part-of: strimzi-user-operator
