apiVersion: v2
name: datadog
description: Datadog Agent
type: application

# This is the chart version.
# This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the Datadog Agent image being deployed.
# This version number should be the same as each time you update Datadog Agent image version.
appVersion: 7.61.0
