{{- range $index, $cronjob := (.Values.cronjobs) }}
  {{- include "spartan.cronjob" (dict "cronjob" $cronjob "Values" $.Values "Chart" $.Chart "Release" $.Release) }}
  {{- if lt $index (sub (len $.Values.cronjobs) 1) }}
---
  {{- end }}
{{- end }}
