{{- if .Values.gatewayApi.enabled -}}
{{- $fullName := include "spartan.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "spartan.labels" . | nindent 4 }}
spec:
{{- with .Values.gatewayApi }}
  parentRefs:
  - name: {{ .gatewayName }}
    namespace: {{ .namespace }}
  hostnames:
  {{- range .httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  {{- toYaml .httpRoute.rules | nindent 2 }}
    backendRefs:
    - name: {{ $fullName }}
      port: 80
{{ end }}
{{ end }}
