{{- if .Values.keda.enabled }}
{{- $fullName := include "spartan.fullname" . -}}
{{- range .Values.keda.authentication }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ $fullName }}-{{ .name }}
spec:
  podIdentity:
    provider: {{ .podIdentity.provider }}
    identityOwner: {{ .podIdentity.identityOwner | default "workload" }}
---
{{- end }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ $fullName }}
spec:
  scaleTargetRef:
    name: {{ $fullName }}
  triggers:
    {{- range .Values.keda.triggers }}
    - type: {{ .type }}
      {{- if .metricType }}
      metricType: {{ .metricType }}
      {{- end }}
      {{- if .authentication }}
      authenticationRef:
        name: {{ $fullName }}-{{ .authentication.name }}
      {{- end }}
      metadata:
        {{- toYaml .metadata | nindent 8 }}
    {{- end }}
---
{{- end }}
