{{- if .Values.gcp.enabled }}
{{- if .Values.gcp.managedCertificate }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ include "spartan.fullname" $ }}-managed-certificate
spec:
  domains:
    {{- toYaml .Values.gcp.managedCertificate.domains | nindent 4 }}
{{- end }}
{{- end }}
