{{- $replicaCount := int .Values.replicaCount }}
{{- $autoscalingMinReplica := int .Values.autoscaling.minReplicas }}
{{- if and .Values.pdb.enabled (or (and (gt $replicaCount 1) (not .Values.autoscaling.enabled)) (and .Values.autoscaling.enabled (gt $autoscalingMinReplica 1))) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "spartan.fullname" . }}
  labels:
    {{- include "spartan.labels" . | nindent 4 }}
    tier: "pdb"
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end  }}
  selector:
    matchLabels:
      {{- include "spartan.selectorLabels" . | nindent 6 }}
{{- end }}
