# Example values for enabling Reloader annotations in spartan chart
# This assumes Reloader is deployed separately via Terraform

# Basic auto-reload configuration
deploymentAnnotations:
  "reloader.stakater.com/auto": "true"

# Example with specific resources
# deploymentAnnotations:
#   "configmap.reloader.stakater.com/reload": "app-config"
#   "configmap.reloader.stakater.com/reload": "database-config"
#   "secret.reloader.stakater.com/reload": "app-secrets"
#   "secret.reloader.stakater.com/reload": "database-secrets"

# Example with search pattern
# deploymentAnnotations:
#   "reloader.stakater.com/search": "true"
#   "reloader.stakater.com/match": "my-app-*"

# Example with mixed annotations
# deploymentAnnotations:
#   "reloader.stakater.com/auto": "true"
#   "custom.reloader.com/team": "platform"
#   "custom.reloader.com/environment": "production"
#   "deployment.kubernetes.io/revision": "1"
#   "monitoring.coreos.com/scrape": "true"

# Your application configuration
image:
  repository: "nginx"
  tag: "latest"

replicaCount: 2

service:
  type: ClusterIP
  port: 80
