name: Create Minor Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: 'write'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update git configuration
        run: |
          git config user.email github-actions@spartan.com
          git config user.name github-actions

      - name: Bump version
        run: |
          ./tools/create_release.sh minor
