name: Helm Check

on: pull_request

env:
  GH_APP_ID: ${{ vars.APP_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

jobs:
  helm-check:
    strategy:
      matrix:
        chart: [ spartan, datadog ]

    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Helm repo add
        if: matrix.chart == 'datadog' # for datadog chart only
        run: |
          helm repo add datadog https://helm.datadoghq.com
          helm repo add prometheus https://prometheus-community.github.io/helm-charts

      - name: Helm dependency build
        if: matrix.chart == 'datadog' # for datadog chart only
        run: helm dependency build ./charts/${{ matrix.chart }}

      - name: helm-check-default
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/${{ matrix.chart }}
          CHART_VALUES: ./charts/${{ matrix.chart }}/values.yaml

      - name: helm-check-enabled-all
        if: matrix.chart == 'spartan' # for spartan chart only
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/spartan
          CHART_VALUES: ./test/values.yaml

      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run helm-unittest
        run: |
          echo "Running unittest for ${{ matrix.chart }}} chart"
          helm unittest "charts/${{ matrix.chart }}"
