name: Helm Check

on: pull_request

env:
  HELM_CHARTS: "spartan"
  GH_APP_ID: ${{ vars.APP_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

jobs:
  helm-check:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: helm-check-default
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/spartan
          CHART_VALUES: ./charts/spartan/values.yaml

      - name: helm-check-enabled-all
        uses: igabaydulin/helm-check-action@0.1.4
        env:
          CHART_LOCATION: ./charts/spartan
          CHART_VALUES: ./test/values.yaml

      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Run helm-unittest
        run: |
          for chart in $HELM_CHARTS
          do
            echo "Running unittest for ${chart} chart"
            helm unittest "charts/${chart}"
          done
