## This workflow will create / update `index.yaml` on `/gh-pages` branch
## whether there is any changes on chart(s),
## and add created helm artifact(s) with version from `Chart.yaml` to Github release.
##
name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'charts/**/Chart.yaml'

env:
  GH_APP_ID: ${{ vars.APP_ID }}
  GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ env.GH_APP_ID }}
          private-key: ${{ env.GH_APP_PRIVATE_KEY }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          token: ${{ steps.github-app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Update git configuration
        run: |
          git config user.email github-actions@spartan.com
          git config user.name github-actions

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: ${{ steps.github-app-token.outputs.token }}
